"""renaming_sn_to_token

Revision ID: 376fa102157d
Revises: b59a0721ac2d
Create Date: 2023-03-26 17:54:41.410463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376fa102157d'
down_revision = 'b59a0721ac2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_token', sa.String(), nullable=False))
    op.drop_column('devices', 'device_serial_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_serial_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('devices', 'device_token')
    # ### end Alembic commands ###
